### ISSUE TITLE
ObjectGenerator generate 의 지원하지 않음과 null 반환을 구분

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#98]
현재 ObjectGenerator 는 아래와 같이 Optional 을 반환하는 generate 메소드가 제공됩니다.

```java
interface ObjectGenerator {

    Optional<Object> generate(ObjectQuery query, ObjectGenerationContext context);

}
```

Generator 구현체가 ObjectQuery 의 지원 대상이 아니라면 `Optional.empty` 를 반환합니다.
Generator 가 [null 을 반환할 수 있다면](https://github.com/JavaUnit/AutoParams/pull/92#discussion_r598360515) `지원하지 않음` 과 `null` 반환을 구분할 필요가 생깁니다.

우선 아래 2가지 중에 하나를 선택할 수 있을거 같은데요. 더 나은 방법이 있을까요? 의견 부탁드립니다. 

1. ObjectGenerator 가 ObjectQuery 지원 가능을 판단하는 API 를 추가한다.
2. generate 가 ObjectQuery 를 지원하지 않는다면, Exception 을 던진다.

--------------------------------------

### Tasks
- [x] GenerationResult 타입 도입
- [x] 모든 generator `GenerationResult generateObject(...)` 구현
- [x] 모든 generator에서 `Optional<Object> generate(...)` 메소드 삭제
- [x] `generateObject` -> `generate` 로 메소드 이름 변경

**Comment by gyuwon** [comment]
`ObjectGenerator`가 `null'을 생성할 수도 값을 생성할 수 없을 수도 있기 때문에 `Optional`이 사용되었습니다.

**Comment by gyuwon** [comment]
헐... 지금 확인해보니 `Optional`은 `null`을 담을 수 없군요.

**Comment by mhyeon-lee** [comment]
@gyuwon 
`null` 이 생성된거는 어떻게 판단해야 할까요?

현재는 `Optional.empty` 가 반환되면 `값을 생성할 수 없다` 로 판단되서 다음 Generator 한테 넘기는거 같습니다.

`null` 이 생성되었음이 판단되면 다음으로 넘기지 않고 어떻게든 null 을 표현해서 반환해야 할거 같습니다.

**Comment by gyuwon** [comment]
그러면 `Optional` 쓸 이유가 없는데...

**Comment by jwChung** [comment]
```java
public class Foo {
    @Nullable
    private String name;
}
```

이런 경우에 `getName()`  임의의 string 값과 null 값도 같이 표현될 수 있는 것을 지원하기 위해서인가요?

**Comment by mhyeon-lee** [comment]
@jwChung 나중엔 그런 케이스도 있지만 당장은 #84 에서 고민이 됩니다.

```java
@ParameterizedTest
@AutoSource
public void test(Builder<Bar> barBuilder) {
    Bar bar = barBuilder.fix(Integer.class, null).build();

    // bar.value == null
}
```

**Comment by mhyeon-lee** [comment]
NullObject 를 만드는 것도 방법 중에 하나가 될 수 있겠네요

**Comment by jwChung** [comment]
네 저도 그 방법이 좋을 것 같네요.

**Comment by jwChung** [comment]
`GenerationResult` 타입을 도입합니다.

**Comment by Rebwon** [comment]
Spring Bean의 경우 interface나 abstract 타입으로 만들어지는 경우가 종종 있는데, 이슈 #101 의 문제 상황을 재현할 때, 현재 구현 상황으로는 ObjectGenerationException이 먼저 발생되어 ParameterResolutionException 자체가 발생하지 않습니다. 꼭 throw를 던져야 하는 건가요..?

**Comment by jwChung** [comment]
@Rebwon ObjectGenerationException 발생은 이 이슈랑 관련이 없어 보이는데요. 여기서 간단하게 논의할 내용도 아닌 것 같아요.

#101 에서 논의하거나 혹시 #94 와 관련 있다면 다시 여시거나, 아니면 새로운 이슈를 만드시는 게 좋을 것 같습니다. :)
